Feature:association
2004-okari/SCHOOL_LIBRARY pull request #3
Opened 2023-10-04 08:53 UTC by 2004-okari

In this pull request, we introduce several new classes and establish relationships between them as per the project requirements.

**Classroom Class:**
- Created a `Classroom` class with an `@label` instance variable, initialized in the constructor.
- Implemented setters and getters for the `@label` instance variable using `attr_accessor`.
- Established a has-many relationship where a classroom can have many students.
- Implemented the belongs-to relationship where a student belongs to a classroom.
- Ensured that when adding a student to a classroom, it also sets the classroom for the student.
- Ensured that when setting the classroom for a student, it also adds the student to the classroom's list of students.

**Book Class:**
- Created a `Book` class with `@title` and `@author` instance variables, initialized in the constructor.
- Implemented setters and getters for the `@title` and `@author` instance variables using `attr_accessor`.

**Rental Class:**
- Created a `Rental` class with an `@date` instance variable, initialized in the constructor.
- Implemented setters and getters for the `@date` instance variable using `attr_accessor`.
- Established a many-to-many (has-many-through) relationship between `Person` and `Book` using the intermediate class `Rental`.
- Created the has-many side of `Book` and `Rental`, where a book can have many rentals.
- Created the belongs-to side of `Rental` and `Book`, where a rental belongs to a book.
- Created the has-many side of `Person` and `Rental`, where a person can have many rentals.
- Created the belongs-to side of `Rental` and `Person`, where a rental belongs to a person.
- Modified the constructor of `Rental` to set both `Book` and `Person`.

This pull request implements the specified class structures and relationships, ensuring that they work as intended.

2023-10-04 09:07 UTC, mikethreels requested changes
Hi Nyandika, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job setting up the associations.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-04 09:07 UTC, mikethreels commented on classroom.rb
> +  attr_accessor :label, :students
- [ ] the association will work this way, however, for security reasons, it is better to make the students only available with the attribute reader instead of the accessor.

2023-10-04 09:07 UTC, mikethreels commented on student.rb
>    end
- [ ] please make sure to make the classroom readable outside the student class as well.

2023-10-04 09:07 UTC, mikethreels commented on book.rb
> +  end
- [ ] great job creating the add_rental method, however, it should look a little different, please have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) for more details.

2023-10-04 09:07 UTC, mikethreels commented on rental.rb
> +  attr_accessor :date
- [ ] to make this association work Getters and Setters for @book and @person instance variables should be present in the rental class

2023-10-04 09:07 UTC, mikethreels commented on rental.rb
> +  end
- [ ] in order for the association to work the constructor of Rental should be modified so Book and Person are set in it to break the many-to-many relationship. please have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship). after updating this you can remove the book and person method below as well.

2023-10-04 09:07 UTC, mikethreels commented on person.rb
> +    rental.person = self
- [ ] good job adding the add_rental method, however, it should look a little different, please have a look at [this article](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship) for more details.

2023-10-05 15:39 UTC, 2004-okari commented on person.rb
> +    rental.person = self
the << is similar to push method

2023-10-05 16:25 UTC, topeogunleye approved these changes
### Hi @2004-okari, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 

1. **Association Security**:
    - 🛡 Great job adjusting the accessibility of the students! It's always a good practice to think about security and limiting access wherever necessary. Using the attribute reader for students instead of the accessor is a commendable move.

2. **Classroom Accessibility**:
    - 📘 Nicely done ensuring that the classroom is readable outside the student class. This enhances the interaction and encapsulation principle between the objects.

3. **Add Rental Method**:
    - 🔄 I noticed that you worked on the `add_rental` method following the feedback. It's great that you're iterating on it, but remember to review the provided article for the ideal structure and functionality.

4. **Rental Class Getters and Setters**:
    - 🗝 Spot-on! Having both getters and setters for `@book` and `@person` instance variables in the rental class is essential for ensuring the associations function correctly.

5. **Rental Constructor Update**:
    - 🏗 Kudos on revisiting the constructor of the `Rental` class. Adjusting it to properly set the `Book` and `Person` is vital to ensure a seamless many-to-many relationship transition. Your effort in addressing this is commendable, and remember, after this update, certain methods might become redundant, so it's a good step to remove them.

In summary, you've made notable progress in addressing the feedback. Keep iterating, refining, and diving deep into the provided resources. Your dedication to improvement is evident!

Keep up the fantastic work! 🚀🧑‍💻
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-06 07:40 UTC, merged